// ═══════════════════════════════════════════════════
// CONFIG.JS — SEMUA DATA YANG BOLEH DIEDIT ADA DI SINI
// (script.js berisi LOGIKA, jangan diedit kalau cuma mau ganti data)
// ═══════════════════════════════════════════════════

// ═══════ KONFIGURASI UMUM ═══════
const CONFIG = {
  heroVideo   : "https://l.top4top.io/m_3779fe6uv1.mp4",
  heroPoster  : "",
  heroBanner  : "",
  avatarImg   : "https://img2.pixhost.to/images/7724/723457563_alip-1778154031488.jpg",
  bgMusic     : "https://files.catbox.moe/til5wh.mp3",
  waliImg     : "",
  waGroup     : "https://chat.whatsapp.com/DEX62QPp12nE86mGyS3grg?s=cl&p=a&ilr=0&amv=3",
  igClass     : "https://www.instagram.com/class8bright_star",
  nglLink     : "",
  tiktokClass : "https://www.tiktok.com/@class8brightstar",
  waChannel   : "https://whatsapp.com/channel/0029VbBKBD9F6smwoAydKr3x",
  waliWa      : "https://wa.me/6285159145010",
  memoriesVideo  : "",
  memoriesPhotos : [
    "https://img2.pixhost.to/images/7724/723458876_alip-1778154364652.jpg",
    "https://img2.pixhost.to/images/7725/723470697_alip-1778157365322.jpg",
    "", "", "", ""
  ],
};

// ═══════ DAFTAR SISWA ═══════
const STUDENTS = [
  { name: "PA DWIKI APRIANTO", photo: "", msg: "Hanya allah yang tau." },
  { name: "ADHYASTA NARARYA AL JAZALI", photo: "", msg: "Kegagalan adalah proses menuju keberhasilan." },
  { name: "AGUNG MAULANA IBRAHIM", photo: "", msg: "Proses tidak akan pernah mengkhianati hasil." },
  { name: "ARFA HAIDAR RAISSA", photo: "", msg: "Diam bukan berarti kalah, tapi sedang menyimpan tenaga." },
  { name: "DAFIN AZKA", photo: "", msg: "Ilmu adalah cahaya, bawa ia ke mana pun kamu pergi." },
  { name: "DHEVANO ARKA PUTRA PRATAMA", photo: "", msg: "Setiap hari adalah kesempatan untuk jadi lebih baik." },
  { name: "FAHREZA MAULANA", photo: "", msg: "Kerja keras hari ini adalah cerita sukses esok hari." },
  { name: "FAUZAN KHODHI LATIF", photo: "", msg: "Yang penting bukan seberapa cepat, tapi seberapa kuat." },
  { name: "HAFIZ FATIHUL AHZA", photo: "", msg: "Mimpi besar dimulai dari langkah kecil yang konsisten." },
  { name: "HAFIZH MALIK SOPIYAN", photo: "", msg: "Belajar tanpa batas, tumbuh tanpa henti." },
  { name: "HAIDAR ALI RASYIDI", photo: "", msg: "Jadilah versi terbaik dirimu, bukan orang lain." },
  { name: "KENNY JULIAN NAKAJIMA", photo: "", msg: "Hidup terlalu singkat untuk tidak bermimpi besar." },
  { name: "KEVIN FAEYZA GUNAWAN", photo: "", msg: "Sukses bukan tentang tujuan, tapi perjalanannya." },
  { name: "MAHER ADEWAN SUHARTA", photo: "", msg: "Tak ada yang mustahil bagi orang yang mau berusaha." },
  { name: "MUHAMMAD ADNAN GHOFARANA", photo: "", msg: "Kesabaran adalah kunci yang membuka pintu keberhasilan." },
  { name: "MUHAMMAD AKHDAAN NUR'AIMAN", photo: "", msg: "Jangan berhenti ketika lelah, berhentilah ketika selesai." },
  { name: "MUHAMMAD DZAKI PURWANDRA S", photo: "", msg: "Setiap tetes keringat adalah benih kesuksesan." },
  { name: "MUHAMMAD FAKHRI", photo: "", msg: "Rendah hati dalam belajar, tinggi semangat dalam berkarya." },
  { name: "MUHAMMAD FAWWAAZ SAPUTRA", photo: "", msg: "Ilmu tanpa amal seperti pohon tanpa buah." },
  { name: "MUHAMMAD RAFIF ALAUNA", photo: "", msg: "Hari ini lebih baik dari kemarin, besok lebih baik dari hari ini." },
  { name: "MUHAMMAD RIZQY ALFARIDZ", photo: "", msg: "Mengapa aku berubah?" },
  { name: "MUHAMMAD WAFIQ ZIHNI", photo: "", msg: "Pikiran yang positif menghasilkan hidup yang luar biasa." },
  { name: "MUHAMMAD WILDAN ALJINAN", photo: "", msg: "Bersyukur atas yang ada, berusaha untuk yang lebih baik." },
  { name: "NIZAM ABYAN FAEZYA", photo: "", msg: "Fokus pada tujuan, bukan pada rintangan." },
  { name: "QOULAN TSAQIILA RIZALUSYIIFA", photo: "", msg: "Jangan bergerak tanpa sepengetahuan Tuhan." },
  { name: "RADINAL AKBAR RUSDANA", photo: "", msg: "Berani bermimpi, lebih berani lagi mewujudkannya." },
  { name: "RADITYO DZAKWAN EFFENDI", photo: "", msg: "Disiplin adalah jembatan antara tujuan dan pencapaian." },
  { name: "RAFASHA ERLANDIKA", photo: "", msg: "Jadikan setiap momen sebagai pelajaran berharga." },
  { name: "RAKA TSAQIF AZZAMY", photo: "", msg: "Kuat bukan berarti tidak pernah jatuh, tapi selalu bangkit." },
  { name: "RHEKSYA MUHAMAD SYAHROZAQ", photo: "", msg: "Karakter yang baik adalah harta yang paling berharga." },
  { name: "SADAD FAIRUZ YUSUP JAMALUDIN", photo: "", msg: "Kejujuran adalah fondasi dari segala keberhasilan." },
  { name: "SAYID HUSEIN SYAMIL", photo: "", msg: "Teruslah belajar, karena ilmu tidak pernah habis." },
  { name: "SYAKIB ASSAKYA", photo: "", msg: "Akhiri setiap hari dengan rasa syukur dan tekad baru." },
];

// ═══════ HARI (dipakai Reminder & Jadwal) ═══════
// Mau tambah/kurangi hari sekolah? Tinggal edit array ini.
const DAYS = [
  { key: 'senin',  id: 'Senin',  betawi: 'Senén',  en: 'Monday',    su: 'Senén'  },
  { key: 'selasa', id: 'Selasa', betawi: 'Selasa', en: 'Tuesday',   su: 'Salasa' },
  { key: 'rabu',   id: 'Rabu',   betawi: 'Rebo',   en: 'Wednesday', su: 'Rebo'   },
  { key: 'kamis',  id: 'Kamis',  betawi: 'Kemis',  en: 'Thursday',  su: 'Kemis'  },
  { key: 'jumat',  id: 'Jumat',  betawi: 'Jumat',  en: 'Friday',    su: 'Jumaah' },
  { key: 'sabtu',  id: 'Sabtu',  betawi: 'Sabtu',  en: 'Saturday',  su: 'Saptu'  },
];

// ═══════ JADWAL PELAJARAN (halaman publik, semua orang bisa lihat) ═══════
// [PENTING] Ini masih KOSONG / CONTOH — Al belum kasih jadwal aslinya.
// Isi tiap hari dengan array {jam, mapel}. Kosongkan array kalau hari itu
// belum ada jadwalnya (nanti otomatis muncul teks "Belum diisi").
const SCHEDULE = {
  senin:  [
    // { jam: "07:00 - 07:40", mapel: "Upacara" },
    // { jam: "07:40 - 08:20", mapel: "Matematika" },
  ],
  selasa: [],
  rabu:   [],
  kamis:  [],
  jumat:  [],
  sabtu:  [],
};

// ═══════ REMINDER — ADMIN & JSONBIN ═══════
//
// [PENTING] Kata sandi admin sudah diganti dari default. Kalau mau ganti lagi:
//   1. Buka halaman Reminder di browser, tekan F12 (console).
//   2. Ketik: generatePasswordHash('kata-sandi-baru-kamu').then(h => console.log(h))
//   3. Copy hasil hash yang muncul, tempel ke REMINDER_CONFIG.adminPasswordHash di bawah.
//
// jsonbinBinId sudah diisi permanen supaya SEMUA ORANG di SEMUA DEVICE otomatis
// nyambung ke data yang sama tanpa perlu tempel manual apapun.
//
const REMINDER_CONFIG = {
  adminPasswordHash: "25ac88ffce648561c6fd1fa23eb0c3eee4e3103b4499c310e033adfc19bb55d6",
  jsonbinApiKey: "$2a$10$0XA/Bap/CiGTnq9yVVCVq.gXRScb.ycMrrQ2.2uKaScStP/rtx.Um",
  jsonbinBinId: "6a6c8672f5f4af5e29d9b05e",
};

// ═══════ BAHASA (Indonesia / Betawi / English / Sunda) ═══════
// Ini menerjemahkan teks UI (menu, judul, tombol, hint). Konten seperti
// quotes, pesan siswa, dan nama tetap apa adanya di semua bahasa.
const LANG_ORDER = ['id', 'betawi', 'en', 'su'];
const LANG_LABEL = { id: 'ID', betawi: 'BE', en: 'EN', su: 'SU' };

const LANG_STRINGS = {
  id: {
    btn_change_lang: "Ganti Bahasa",
    btn_toggle_music: "Putar / Jeda Musik",
    btn_toggle_theme: "Mode Gelap",
    label_menu: "Menu",
    label_page_nav: "Navigasi Halaman",
    nav_home: "Beranda", nav_students: "Absensi", nav_schedule: "Jadwal",
    nav_memories: "Kenangan", nav_reminder: "Reminder",
    label_info: "Info",
    label_quotes: "Quotes",
    label_info_kelas: "Informasi Kelas",
    label_kelas_word: "Kelas", label_angkatan_word: "Angkatan", label_siswa_word: "Siswa",
    label_wali_kelas: "Wali Kelas",
    label_hubungi_walas: "Hubungi Walas",
    label_walas: "Walas",
    label_keseharian: "Keseharian",
    skill_kompak: "Kompak", skill_belajar: "Belajar", skill_olahraga: "Olahraga", skill_musik: "Musik", skill_gaming: "Gaming",
    label_developer: "developer",
    label_daftar_absensi: "Daftar Absensi",
    label_tap_untuk_pesan: "Ketuk untuk lihat pesan",
    label_kenangan_indah: "Kenangan Indah",
    label_galeri_foto: "Galeri Foto",
    label_video_kenangan: "Video Kenangan",
    label_momen_berharga: "Momen Berharga",
    label_jadwal_pelajaran: "Jadwal Pelajaran",
    label_jadwal_subtitle: "Bisa dilihat semua orang",
    label_pilih_hari: "Pilih Hari",
    label_jadwal_kosong: "Jadwal untuk hari ini belum diisi admin.",
    reminder_title: "Reminder Harian",
    reminder_subtitle: "Khusus Admin",
    reminder_gate_title: "Akses Terbatas",
    reminder_gate_text: "Halaman ini hanya untuk admin kelas. Masukkan kata sandi untuk melanjutkan.",
    reminder_pw_placeholder: "KATA SANDI",
    reminder_pw_submit: "Masuk",
    reminder_pw_error: "Kata sandi salah.",
    label_tanggal: "Tanggal", label_seragam: "Seragam", label_mapel: "Mata Pelajaran",
    label_tugas: "Tugas", label_piket: "Piket", label_catatan: "Catatan",
    btn_tambah_baris: "Tambah Baris",
    btn_simpan_perubahan: "Simpan Perubahan",
    btn_tersimpan_ok: "Tersimpan!",
    label_preview_pesan: "Preview Pesan",
    btn_salin_pesan: "Salin Pesan", btn_tersalin: "Tersalin!",
    btn_buka_grup: "Buka Grup WA",
    reminder_hint_wa: "WhatsApp tidak mengizinkan pengiriman otomatis ke grup. Salin pesan, lalu tempel & kirim manual di grup yang terbuka.",
    label_sync_settings: "Pengaturan Sinkronisasi (Bin ID)",
    binid_placeholder: "Bin ID akan muncul di sini otomatis",
    btn_simpan_binid: "Simpan",
    btn_cari_binid: "Cari Bin ID Otomatis",
    binid_hint: "Bin ID sudah diatur permanen lewat config.js sehingga semua orang otomatis nyambung. Kolom ini hanya untuk override manual kalau sewaktu-waktu perlu pindah ke bin lain.",
    btn_keluar: "Keluar",
    placeholder_tanggal_input: "cth: Senin, 4 Agustus 2026",
    placeholder_isi_baris: "Isi baris...",
    sync_status_prefix: "Status sinkronisasi:",
    sync_idle: "-",
  },
  betawi: {
    btn_change_lang: "Ganti Bahasa",
    btn_toggle_music: "Puter / Stop Musik",
    btn_toggle_theme: "Mode Gelap",
    label_menu: "Menu",
    label_page_nav: "Navigasi Ané",
    nav_home: "Beranda", nav_students: "Absen", nav_schedule: "Jadwal",
    nav_memories: "Kenangan", nav_reminder: "Reminder",
    label_info: "Info",
    label_quotes: "Kate-Kate",
    label_info_kelas: "Info Kelas",
    label_kelas_word: "Kelas", label_angkatan_word: "Angkatan", label_siswa_word: "Murid",
    label_wali_kelas: "Wali Kelas",
    label_hubungi_walas: "Kontak Walas",
    label_walas: "Walas",
    label_keseharian: "Keseharian",
    skill_kompak: "Kompak", skill_belajar: "Belajar", skill_olahraga: "Olahraga", skill_musik: "Musik", skill_gaming: "Maen Game",
    label_developer: "developer",
    label_daftar_absensi: "Daptar Absen",
    label_tap_untuk_pesan: "Pencet buat liat pesen",
    label_kenangan_indah: "Kenangan Indah",
    label_galeri_foto: "Galeri Foto",
    label_video_kenangan: "Video Kenangan",
    label_momen_berharga: "Momen Berharga",
    label_jadwal_pelajaran: "Jadwal Pelajaran",
    label_jadwal_subtitle: "Bisa diliat semua orang",
    label_pilih_hari: "Pilih Hari",
    label_jadwal_kosong: "Jadwal ari ini belom diisi ame admin.",
    reminder_title: "Reminder Arian",
    reminder_subtitle: "Cuma Buat Admin",
    reminder_gate_title: "Ga Bisa Masuk Sembarangan",
    reminder_gate_text: "Ini halaman cuma buat admin kelas. Masukin kate sandi dulu ye.",
    reminder_pw_placeholder: "KATE SANDI",
    reminder_pw_submit: "Masuk",
    reminder_pw_error: "Kate sandinye salah tuh.",
    label_tanggal: "Tanggal", label_seragam: "Seragam", label_mapel: "Mata Pelajaran",
    label_tugas: "Tugas", label_piket: "Piket", label_catatan: "Catetan",
    btn_tambah_baris: "Tambah Baris",
    btn_simpan_perubahan: "Simpen Perubahannye",
    btn_tersimpan_ok: "Udeh Kesimpen!",
    label_preview_pesan: "Liat Dulu Pesennye",
    btn_salin_pesan: "Kopi Pesen", btn_tersalin: "Udeh Kekopi!",
    btn_buka_grup: "Buka Grup WA",
    reminder_hint_wa: "WhatsApp emang gak bisa langsung kirim ke grup. Kopi pesennye dulu, abis itu paste & kirim sendiri di grup yang kebuka.",
    label_sync_settings: "Setelan Singkronisasi (Bin ID)",
    binid_placeholder: "Bin ID bakal muncul di sini otomatis",
    btn_simpan_binid: "Simpen",
    btn_cari_binid: "Cariin Bin ID Otomatis",
    binid_hint: "Bin ID-nye udeh diatur permanen di config.js jadi semua orang otomatis nyambung. Kolom ini cuma buat ganti manual kalo sewaktu-waktu mesti pindah ke bin laen.",
    btn_keluar: "Keluar",
    placeholder_tanggal_input: "cth: Senén, 4 Agustus 2026",
    placeholder_isi_baris: "Isi barisnye...",
    sync_status_prefix: "Status singkronisasi:",
    sync_idle: "-",
  },
  en: {
    btn_change_lang: "Change Language",
    btn_toggle_music: "Play / Pause Music",
    btn_toggle_theme: "Dark Mode",
    label_menu: "Menu",
    label_page_nav: "Page Navigation",
    nav_home: "Home", nav_students: "Roll Call", nav_schedule: "Schedule",
    nav_memories: "Memories", nav_reminder: "Reminder",
    label_info: "Info",
    label_quotes: "Quotes",
    label_info_kelas: "Class Info",
    label_kelas_word: "Class", label_angkatan_word: "Batch", label_siswa_word: "Students",
    label_wali_kelas: "Homeroom Teacher",
    label_hubungi_walas: "Contact Teacher",
    label_walas: "Homeroom",
    label_keseharian: "Daily Life",
    skill_kompak: "United", skill_belajar: "Studious", skill_olahraga: "Sporty", skill_musik: "Music", skill_gaming: "Gaming",
    label_developer: "developer",
    label_daftar_absensi: "Roll Call List",
    label_tap_untuk_pesan: "Tap to see message",
    label_kenangan_indah: "Sweet Memories",
    label_galeri_foto: "Photo Gallery",
    label_video_kenangan: "Memory Video",
    label_momen_berharga: "Precious Moments",
    label_jadwal_pelajaran: "Class Schedule",
    label_jadwal_subtitle: "Visible to everyone",
    label_pilih_hari: "Select Day",
    label_jadwal_kosong: "The schedule for this day hasn't been filled in yet.",
    reminder_title: "Daily Reminder",
    reminder_subtitle: "Admin Only",
    reminder_gate_title: "Restricted Access",
    reminder_gate_text: "This page is for class admins only. Enter the password to continue.",
    reminder_pw_placeholder: "PASSWORD",
    reminder_pw_submit: "Enter",
    reminder_pw_error: "Wrong password.",
    label_tanggal: "Date", label_seragam: "Uniform", label_mapel: "Subjects",
    label_tugas: "Assignments", label_piket: "Cleaning Duty", label_catatan: "Notes",
    btn_tambah_baris: "Add Line",
    btn_simpan_perubahan: "Save Changes",
    btn_tersimpan_ok: "Saved!",
    label_preview_pesan: "Message Preview",
    btn_salin_pesan: "Copy Message", btn_tersalin: "Copied!",
    btn_buka_grup: "Open WA Group",
    reminder_hint_wa: "WhatsApp doesn't allow auto-sending to a group. Copy the message, then paste & send it manually in the group that opens.",
    label_sync_settings: "Sync Settings (Bin ID)",
    binid_placeholder: "Bin ID will appear here automatically",
    btn_simpan_binid: "Save",
    btn_cari_binid: "Auto-Find Bin ID",
    binid_hint: "The Bin ID is already set permanently in config.js so everyone connects automatically. This field is only for a manual override if you ever need to switch to a different bin.",
    btn_keluar: "Log Out",
    placeholder_tanggal_input: "e.g. Monday, August 4 2026",
    placeholder_isi_baris: "Enter item...",
    sync_status_prefix: "Sync status:",
    sync_idle: "-",
  },
  su: {
    btn_change_lang: "Ganti Basa",
    btn_toggle_music: "Puter / Eureunkeun Musik",
    btn_toggle_theme: "Mode Poek",
    label_menu: "Menu",
    label_page_nav: "Navigasi Halaman",
    nav_home: "Bumi", nav_students: "Absén", nav_schedule: "Jadwal",
    nav_memories: "Kenangan", nav_reminder: "Reminder",
    label_info: "Info",
    label_quotes: "Kekecapan",
    label_info_kelas: "Inpormasi Kelas",
    label_kelas_word: "Kelas", label_angkatan_word: "Angkatan", label_siswa_word: "Siswa",
    label_wali_kelas: "Wali Kelas",
    label_hubungi_walas: "Hubungan Walas",
    label_walas: "Walas",
    label_keseharian: "Sapopoé",
    skill_kompak: "Kompak", skill_belajar: "Diajar", skill_olahraga: "Olahraga", skill_musik: "Musik", skill_gaming: "Gaming",
    label_developer: "developer",
    label_daftar_absensi: "Daptar Absén",
    label_tap_untuk_pesan: "Pencét pikeun ningali pesen",
    label_kenangan_indah: "Kenangan Éndah",
    label_galeri_foto: "Galeri Poto",
    label_video_kenangan: "Video Kenangan",
    label_momen_berharga: "Momén Berharga",
    label_jadwal_pelajaran: "Jadwal Pangajaran",
    label_jadwal_subtitle: "Bisa ditingali ku sadayana",
    label_pilih_hari: "Pilih Poé",
    label_jadwal_kosong: "Jadwal poé ieu can dieusian ku admin.",
    reminder_title: "Reminder Sapopoé",
    reminder_subtitle: "Khusus Admin",
    reminder_gate_title: "Aksés Kawates",
    reminder_gate_text: "Halaman ieu khusus admin kelas. Asupkeun kecap sandi heula.",
    reminder_pw_placeholder: "KECAP SANDI",
    reminder_pw_submit: "Asup",
    reminder_pw_error: "Kecap sandina salah.",
    label_tanggal: "Tanggal", label_seragam: "Seragam", label_mapel: "Pelajaran",
    label_tugas: "Tugas", label_piket: "Piket", label_catatan: "Catetan",
    btn_tambah_baris: "Tambah Baris",
    btn_simpan_perubahan: "Simpen Parobahan",
    btn_tersimpan_ok: "Parantos Kasimpen!",
    label_preview_pesan: "Ningali Pesen Heula",
    btn_salin_pesan: "Salin Pesen", btn_tersalin: "Parantos Kasalin!",
    btn_buka_grup: "Buka Grup WA",
    reminder_hint_wa: "WhatsApp teu ngawidian ngirim otomatis ka grup. Salin pesen heula, tuluy témpél sarta kirim manual di grup nu muka.",
    label_sync_settings: "Setelan Singkronisasi (Bin ID)",
    binid_placeholder: "Bin ID bakal muncul otomatis di dieu",
    btn_simpan_binid: "Simpen",
    btn_cari_binid: "Panggihan Bin ID Otomatis",
    binid_hint: "Bin ID parantos diatur permanén dina config.js supados sadayana otomatis nyambung. Kolom ieu ngan kanggo ngaganti manual upami kedah pindah ka bin sanés.",
    btn_keluar: "Kaluar",
    placeholder_tanggal_input: "ct: Senén, 4 Agustus 2026",
    placeholder_isi_baris: "Eusian baris...",
    sync_status_prefix: "Status singkronisasi:",
    sync_idle: "-",
  },
};
